backend:
  name: github
  repo: andreluiz05/semearfitness
  branch: main

collections:
  - name: home
    label: Home
    files:
      - name: home
        label: Home
        file: data/home.yml
        fields:
          - { label: TÃ­tulo, name: hero_titulo, widget: string }