backend:
  name: test-repo

media_folder: "/"
public_folder: "/"

collections:
  - name: "teste"
    label: "Painel Teste"
    files:
      - label: "Teste"
        name: "teste"
        file: "data/teste.yml"
        fields:
          - { label: "Texto de teste", name: "texto", widget: "string" }